#!bin/bash


# error precaution.
set -e
# unzip folder
DIR='app/main'
# default zip file name.
ZIP_FILE_NAME='zipped'
# get zip file from variable or use default.
ZIP_LINK="${ZIP_LINK:-https://codeload.github.com/code-rgb/USERGE-X/zip/alpha}"
# get cmd from variable or use default.
LAUNCH_APP_CMD="${LAUNCH_APP_CMD:-bash run}"
# create main directory.
mkdir -p "app/main"
# fetches latest build.
wget "$ZIP_LINK" -O "app/$ZIP_FILE_NAME.zip"
# unzipping.
unzip "app/$ZIP_FILE_NAME.zip" -d "$DIR"
#run main application.
cd $DIR/*
pip3 install -U setuptools setuptools-scm wheel && pip3 install --no-cache-dir -r requirements.txt
$LAUNCH_APP_CMD
# stress relief.
sleep 5

#heroku commit
